export { default as fbImg } from 'assets/Images/FbImg.svg';
export { default as instaImg } from 'assets/Images/InstaImg.svg';
export { default as twitterImg } from 'assets/Images/TwitterImg.svg';
export { default as linkedinImg } from 'assets/Images/LinkedInImg.svg';
export { default as eventImg } from 'assets/Images/eventImage.svg';
export { default as LeftImg } from 'assets/Images/LeftIcon.svg';
export { default as RightImg } from 'assets/Images/RightIcon.svg';
export { default as linkImg } from 'assets/Images/Link.svg';
export { default as droppedImg } from 'assets/Images/dropedImg.svg';
